version: "2"
services:
  redis-server:
    image: "redis"

  python-server:
    image: "thswpvm/pet-meeting-ml"
    ports:
      - 5000:5000

  server:
    image: "thswpvm/pet-meeting-server"
    depends_on:
      - redis-server
      - python-server
    ports:
      - 4000:4000

  server:
    image: "thswpvm/pet-meeting-client"
    depends_on:
      - server
    ports:
      - 3000:3000
